---
- name: Configure Ubuntu 24.04 VM on Proxmox
  hosts: localhost
  gather_facts: no
  vars:
    proxmox_host: "192.168.1.241:8006"
    proxmox_user: "root"
    proxmox_password: "{{ secrets.PROXMOX_PASSWORD }}"
    node: "pve" # Replace with your Proxmox node name
    vm_id: 101  # Unique VM ID
    vm_name: "ubuntu-vm"
    storage: "local-lvm"
    iso_storage: "local"
    iso_file: "ubuntu-24.04-live-server-amd64.iso"
    disk_size: "30G"
    memory: 2048
    cores: 2

  tasks:
    - name: Create VM on Proxmox
      community.general.proxmox_kvm:
        api_host: "{{ proxmox_host }}"
        api_user: "{{ proxmox_user }}"
        api_password: "{{ proxmox_password }}"
        node: "{{ node }}"
        vmid: "{{ vm_id }}"
        name: "{{ vm_name }}"
        memory: "{{ memory }}"
        cores: "{{ cores }}"
        state: present
      delegate_to: localhost
    
    - name: Add CDROM device to VM
      community.general.proxmox_cdrom:
        api_host: "{{ proxmox_host }}"
        api_user: "{{ proxmox_user }}"
        api_password: "{{ proxmox_password }}"
        node: "{{ node }}"
        vmid: "{{ vm_id }}"
        file: "{{ iso_file }}"
        state: present
      delegate_to: localhost
    
    - name: Add disks to VM
      community.general.proxmox_disk:
        api_host: "{{ proxmox_host }}"
        api_user: "{{ proxmox_user }}"
        api_password: "{{ proxmox_password }}"
        node: "{{ node }}"
        vmid: "{{ vm_id }}"
        size: "{{ disk_size }}"
        type: scsi
        format: qcow2
        state: present
      delegate_to: localhost
