name: Start Proxmox VM

on:
  push:
    branches:
      - main

jobs:
  start-vm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Ansible
        run: |
          pip install ansible

      - name: Run Ansible Playbook
        env:
          PROXMOX_HOST: ${{ secrets.PROXMOX_HOST }}
          PROXMOX_USER: ${{ secrets.PROXMOX_USER }}
          PROXMOX_PASSWORD: ${{ secrets.PROXMOX_PASSWORD }}
        run: |
          ansible-playbook configure_vm.yml \
            -e proxmox_host=$PROXMOX_HOST \
            -e proxmox_user=$PROXMOX_USER \
            -e proxmox_password=$PROXMOX_PASSWORD
