name: Start Proxmox VM

on:
  push:
    branches:
      - main

jobs:
  start-vm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Ansible
        run: |
          pip install ansible

      - name: Start Proxmox VM
        run: |
          ansible-playbook -i proxmox-host, configure_vm.yml

      - name: Wait for VM to start
        run: |
          sleep 60 # wait for 1 minute
